name: Configure Environment Variables
description: Configure environment variables for Filecoin FFI

runs:
  using: 'composite'
  steps:
    - run: |
        echo "FIL_PROOFS_PARAMETER_CACHE=${GITHUB_WORKSPACE}/filecoin-proof-parameters/" >> $GITHUB_ENV
        echo 'GO111MODULE=on' >> $GITHUB_ENV
        echo 'RUST_LOG=info' >> $GITHUB_ENV
        echo "GOPATH=${HOME}/go" >> $GITHUB_ENV
      shell: bash
    - run: |
        echo "/usr/local/go/bin" >> $GITHUB_PATH
        echo "${GOPATH}/bin" >> $GITHUB_PATH
        echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
        echo "${HOME}/.bin" >> $GITHUB_PATH
      shell: bash
    - if: runner.os == 'Linux' && runner.arch == 'ARM64'
      uses: Jimver/cuda-toolkit@9b295696791d75d658d8de64c4a85097ad8abeaf # v0.2.16
    - if: runner.os == 'macOS'
      run: |
        ls "/Applications" | grep "Xcode_"
        sudo xcode-select -s "/Applications/Xcode_14.3.1.app"
        echo "CPATH=$(brew --prefix)/include" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$(brew --prefix)/lib" >> $GITHUB_ENV
      shell: bash
    - if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y valgrind ocl-icd-opencl-dev libssl-dev libhwloc-dev nvidia-cuda-toolkit g++-10
        # Downgrade to GCC 10, as CUDA 11 doesn't play nice with GCC 11
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-10 10
        sudo update-alternatives --set c++ /usr/bin/g++-10
      shell: bash
    - if: runner.os == 'macOS'
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install pkg-config md5sha1sum jq hwloc libmx || brew link --overwrite python@2
      shell: bash
    - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
      with:
        toolchain: 1.73
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'
