name: Configure Environment Variables
description: Configure environment variables for Filecoin FFI

runs:
  using: 'composite'
  steps:
    - run: |
        echo "FIL_PROOFS_PARAMETER_CACHE=${GITHUB_WORKSPACE}/filecoin-proof-parameters/" >> $GITHUB_ENV
        echo 'GO111MODULE=on' >> $GITHUB_ENV
        echo 'RUST_LOG=info' >> $GITHUB_ENV
        echo "GOPATH=${HOME}/go" >> $GITHUB_ENV
        echo "CARGO_TERM_COLOR=never" >> $GITHUB_ENV
      shell: bash
    - run: |
        echo "/usr/local/go/bin" >> $GITHUB_PATH
        echo "${GOPATH}/bin" >> $GITHUB_PATH
        echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
        echo "${HOME}/.bin" >> $GITHUB_PATH
      shell: bash
    - if: runner.os == 'macOS'
      run: |
        echo "CPATH=$(brew --prefix)/include" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$(brew --prefix)/lib" >> $GITHUB_ENV
      shell: bash
    - if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y valgrind ocl-icd-opencl-dev libssl-dev libhwloc-dev nvidia-cuda-toolkit pkgconf
      shell: bash
    - if: runner.os == 'macOS'
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install md5sha1sum hwloc
      shell: bash
    - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
      with:
        toolchain: 1.73
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'
