// WARNING: This file has automatically been generated 
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../ffi-common.h"
#include "../filcrypto-v2.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

