// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_v2

/*
#cgo CXXFLAGS: -std=c++11
#cgo LDFLAGS: -L${SRCDIR}/.. -lstdc++ -lfilcrypto_v2
#cgo pkg-config: ${SRCDIR}/../filcrypto-v2.pc
#include "../ffi-common.h"
#include "../filcrypto-v2.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// FilRegisteredPoStProof as declared in filecoin-ffi/filcrypto-v2.h:36
type FilRegisteredPoStProof int32

// FilRegisteredPoStProof enumeration from filecoin-ffi/filcrypto-v2.h:36
const (
	FilRegisteredPoStProofStackedDrgWinning2KiBV2   FilRegisteredPoStProof = C.fil_RegisteredPoStProof_StackedDrgWinning2KiBV2
	FilRegisteredPoStProofStackedDrgWinning8MiBV2   FilRegisteredPoStProof = C.fil_RegisteredPoStProof_StackedDrgWinning8MiBV2
	FilRegisteredPoStProofStackedDrgWinning512MiBV2 FilRegisteredPoStProof = C.fil_RegisteredPoStProof_StackedDrgWinning512MiBV2
	FilRegisteredPoStProofStackedDrgWinning32GiBV2  FilRegisteredPoStProof = C.fil_RegisteredPoStProof_StackedDrgWinning32GiBV2
	FilRegisteredPoStProofStackedDrgWinning64GiBV2  FilRegisteredPoStProof = C.fil_RegisteredPoStProof_StackedDrgWinning64GiBV2
	FilRegisteredPoStProofStackedDrgWindow2KiBV2    FilRegisteredPoStProof = C.fil_RegisteredPoStProof_StackedDrgWindow2KiBV2
	FilRegisteredPoStProofStackedDrgWindow8MiBV2    FilRegisteredPoStProof = C.fil_RegisteredPoStProof_StackedDrgWindow8MiBV2
	FilRegisteredPoStProofStackedDrgWindow512MiBV2  FilRegisteredPoStProof = C.fil_RegisteredPoStProof_StackedDrgWindow512MiBV2
	FilRegisteredPoStProofStackedDrgWindow32GiBV2   FilRegisteredPoStProof = C.fil_RegisteredPoStProof_StackedDrgWindow32GiBV2
	FilRegisteredPoStProofStackedDrgWindow64GiBV2   FilRegisteredPoStProof = C.fil_RegisteredPoStProof_StackedDrgWindow64GiBV2
)

// FilRegisteredSealProof as declared in filecoin-ffi/filcrypto-v2.h:44
type FilRegisteredSealProof int32

// FilRegisteredSealProof enumeration from filecoin-ffi/filcrypto-v2.h:44
const (
	FilRegisteredSealProofStackedDrg2KiBV2   FilRegisteredSealProof = C.fil_RegisteredSealProof_StackedDrg2KiBV2
	FilRegisteredSealProofStackedDrg8MiBV2   FilRegisteredSealProof = C.fil_RegisteredSealProof_StackedDrg8MiBV2
	FilRegisteredSealProofStackedDrg512MiBV2 FilRegisteredSealProof = C.fil_RegisteredSealProof_StackedDrg512MiBV2
	FilRegisteredSealProofStackedDrg32GiBV2  FilRegisteredSealProof = C.fil_RegisteredSealProof_StackedDrg32GiBV2
	FilRegisteredSealProofStackedDrg64GiBV2  FilRegisteredSealProof = C.fil_RegisteredSealProof_StackedDrg64GiBV2
)
